package com.myspace.rest_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class git implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public git() {
    }




}