package com.myspace.rest_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class test4 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;

	public test4() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public test4(java.lang.String name) {
		this.name = name;
	}

}